require:
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  SuggestExtensions: false
  EnabledByDefault: true
  Exclude:
    - '**/Rakefile'
    - '**/config.ru'
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/support/doorkeeper_configuration.rb'
    - "lib/tasks/**/*"
    - "**/vendor/**/*"
    - "./vendor/**/*"
    - "vendor/**/*"
    - "vendor/*"
    - "vendor/"
    - "vendor"
    - "node_modules/**/*"

## Style
Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

# if we enable this Cop will brake too many specs.
Style/StringHashKeys:
  Enabled: false

# if we enable this Cop will brake too many specs.
Style/Send:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/ImplicitRuntimeError:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Style/ClassMethodsDefinitions:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Copyright:
  Enabled: false

Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/**/*'
    - 'app/models/**/*'
    - 'app/serializers/**/*'

## Lint
Lint/NumberConversion:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

## Layout
Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

## Metrics
Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - '**/*_spec.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'spec/support/api/v1/request_helpers.rb'

## RSpec
RSpec/AlignLeftLetBrace:
  Enabled: false

RSpec/AlignRightLetBrace:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/Pending:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 5

RSpec/LetSetup:
  Exclude:
    - 'spec/services/adapters/service_providers/sendgrid_email_spec.rb'
    - 'spec/services/adapters/channels/email_adapter_spec.rb'

RSpec/ScatteredSetup:
  Exclude:
    - 'spec/integration/**/*'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/integration/**/*'

RSpec/VariableName:
  Exclude:
    - 'spec/integration/**/*'

## Performance
Performance:
  Exclude:
    - '**/test/**/*'
